name = "Negin"
lastname = "Kheirmand"
rol = "Undergraduate Student"
email = "neginkheirmand@gmail.com"
phone = "+98 939 079-7155"
birthday = "April 7, 2001"
location = "Tehran, Iran"
avatar = "./config/assets/avatars/avatar.jpeg"
username = "neginkheirmand" # <-- github user name

# Long presentation
presentation = """
Hello👋😊
I'm **Negin Kheirmand**, a driven computer engineer with a deep passion for innovation and problem-solving. My journey into technology began at **17** with a milestone achievement—winning second place at **Iran Open 2018** in the **Virtual Rescue League** while still in high school, competing alongside university teams. This experience sparked my enduring commitment to pushing boundaries in **computer science**.

I pursued my Bachelor's degree at **Amirkabir University of Technology**, one of the top institutions in Iran, where I focused on **machine learning** and its applications in impactful projects. One of these was **PenSLR**, a glove-based system powered by **deep learning** for **Persian Sign Language recognition**. This project introduced novel **ensembling techniques** to improve prediction accuracy and contributed a new **PSL dataset**, filling a significant gap in the field.

Another key project involved modeling **information spread** in **complex networks** using **convolutional neural networks**. I developed a framework to rank **influential nodes** in networks by extracting **graph features** and simulating information diffusion using the **SIR model**. This work combined theoretical insights in **network science** with practical applications in **graph-based machine learning**.

What drives my work is a unique combination of **constant drive to innovate** and apply my knowledge to **real-world problems**. Throughout my academic journey, I was driven by **curiosity** and a desire to create solutions that address meaningful challenges.

Beyond technical projects, my role as **Head of Communications** in the **Student Council** for two years allowed me to foster connections within the academic community. It was during this time that I discovered my passion for collaboration, whether it was organizing events, mentoring peers, or working with friends to turn innovative ideas into reality. These experiences not only honed my teamworking and organizational skills but also deepened my commitment to using technology to address meaningful challenges.

With a strong foundation in these fields, I’m constantly motivated to expand my knowledge and apply my expertise to tackle cutting-edge challenges and contribute to advancements in **AI** and **machine learning**.
"""

# Short presentation (add this part)
short_presentation = """
I'm Negin Kheirmand, a computer engineering graduate from Amirkabir University of Technology. At 17, I made my mark by winning second place in the Iran Open 2018 Virtual Rescue League, sparking my passion for innovative technology.
My academic journey focused on machine learning, with standout projects like PenSLR—a deep learning system for Persian Sign Language recognition that introduced novel ensembling techniques and created a new PSL dataset.  I also worked on modeling information spread in complex networks, developing a framework to rank influential nodes in networks using graph features and the SIR model.
As Head of Communications in the Student Council, I honed my teamworking and collaboration skills while working to transform innovative ideas into reality. Driven by curiosity, I'm particularly excited about exploring human-computer interaction, blockchain technologies, DevOps, graph theory, and computer vision—fields where technology can create meaningful, innovative solutions.
"""
