name = "Negin"
lastname = "Kheirmand"
rol = "Undergraduate Student"
email = "neginkheirmand@gmail.com"
phone = "+98 939 079-7155"
birthday = "April 7, 2001"
location = "Tehran, Iran"
avatar = "./config/assets/avatars/avatar.jpeg"
username = "neginkheirmand" # <-- github user name
presentation = """
#TODO
Hello, I'm Negin Kheirmand, a driven computer engineer with a deep passion for innovation and problem-solving. My journey into technology began at 17 with a milestone achievement—winning second place at Iran Open 2018 in the Virtual Rescue League while still in high school, competing alongside university teams. This experience sparked my enduring commitment to pushing boundaries in computer science.

I pursued my Bachelor's degree at Amirkabir University of Technology, one of the top institutions in Iran, where I focused on machine learning and its applications in impactful projects. One of these was PenSLR, a glove-based system powered by deep learning for Persian Sign Language recognition. This project introduced novel ensembling techniques to improve prediction accuracy and contributed a new PSL dataset, filling a significant gap in the field.

Another key project involved modeling information spread in complex networks using convolutional neural networks. I developed a framework to rank influential nodes in networks by extracting graph features and simulating information diffusion using the SIR model. This work combined theoretical insights in network science with practical applications in graph-based machine learning.

What drives my work is a unique combination of technical expertise and a constant drive to innovate and apply my knowledge to real-world problems. Throughout my academic journey, I was driven by curiosity and a desire to create solutions that address meaningful challenges.

Beyond technical projects, my role as Head of Communications in the Student Council for two years allowed me to foster connections within the academic community. It was during this time that I discovered my passion for collaboration, whether it was organizing events, mentoring peers, or working with friends to turn innovative ideas into reality. These experiences not only honed my leadership and organizational skills but also deepened my commitment to using technology to address meaningful challenges.

With a strong foundation in these fields, I’m constantly motivated to expand my knowledge and apply my expertise to tackle cutting-edge challenges and contribute to advancements in AI and machine learning.
"""
