############## Education config #################
#################################################
[[education]]
title = "Salam Resalat High School, Tehran, Iran"
timeline = "2016 — 2019"
discipline = "Mathematics & Physics"
description = "GPA: 18.52/20 = 3.9/4"

[[education]]
title = "Amirkabir University of Technology, Tehran, Iran"
timeline = "2019 — 2024"
discipline = "Computer Engineering"
description = "GPA: 18.16/20 = 3.83/4"

############## Research config ################
#################################################

[[research]]
title = "Undergraduate Research Assistant"
timeline = "Feb 2022 — Jun 2022"
institution = "Amirkabir Uni. of Tech."
supervisor = "Dr. Reza Safabakhsh"
description = "As part of the ‘Research and Technical Representation’ course at AUT, I conducted an in-depth study on <b>classic edge detection algorithms for grayscale images</b> . The research included:"
bullets = [
    "Conducting a comprehensive literature review on traditional edge detection methods",
    "Implementing algorithms such as Sobel, Prewitt, Roberts Cross, LoG, Boolean Function, and Canny using OpenCV, followed by a comparative analysis of their performance"
]

[[research]]
title = "Undergraduate Research Assistant"
timeline = "Jan 2022 — Apr 2024"
institution = "Amirkabir Uni. of Tech."
supervisor = "Dr. Hamed Farbeh"
description = "In my first academic paper, my colleagues and I developed a cutting-edge <b>sign language recognition system</b>. Our main contributions included:"
bullets = [
    "Designing a specialized sign language glove equipped with Arduino and five flexible sensors",
    "Collecting the largest Persian Sign Language dataset at the time.",
    "Implementing an end-to-end deep learning framework for accurate sign language recognition using CTC loss function",
    "Introducing a novel ensembling algorithm for grammar-agnostic sequence-to-sequence tasks"
]

[[research]]
title = "Undergraduate Research Assistant"
timeline = "Apr 2024 — Dec 2024"
institution = "Amirkabir Uni. of Tech."
supervisor = "Dr. Mostafa Chehreghani"
description = "For my Bachelor's thesis, I implemented a framework to <b>rank influential nodes in complex networks</b> using convolutional neural networks. The project was highly inspired by this paper included:"  
bullets = [  
    "<b>Extracting node features</b> using different centrality metrics to capture local topological information",  
    "Constructing <b>one-hop adjacency matrices and multi-scale feature embeddings</b> for nodes",  
    "Training a <b>convolutional neural network to predict node influence scores</b> as a regression task",  
    "Generating ground truth labels using the <b>SIR</b> model to simulate information diffusion",  
    "Evaluating the framework against benchmarks on real-world and synthetic networks using <b>Kendall's τ and MAP metrics</b>",  
    "Implementing a visual dashboard enhance project usability for target users"
]  

############## Work config ################
#################################################
[[work]]
title = "Back-end Developer"
company = "Hasin Group"
timeline = "Mar 2022 - Apr 2023"
city = "Tehran"
country = "Iran"
description = "this is the description for the shenasa work i did"
bullets = [
    "Architected and implemented a suite of multiple scalable REST API services for a banking client, leveraging microservices architecture to enhance system performance and modularity",
    "Independently conceptualized, designed, and developed a comprehensive microservices chassis, taking sole responsibility for creating a robust foundational framework that enabled future service expansion and integration",
    "Engineered backend solutions using C#, optimizing application reliability, performance, and scalability through strategic architectural design",
    "Collaborated with cross-functional teams to develop and maintain high-performance, production-grade microservices that met critical banking industry standards"
]

[[work]]
title = "System Administrator & Blockchain Researcher"
company = "Shenasa (Chainova Studio)"
timeline = "Dec 2020 - Sep 2021"
city = "Tehran"
country = "Iran"
description = "Since i held two positions in this company i have divided my achievements in two different "
bullets = [
   "Managed critical infrastructure services for multiple startups, supporting key database technologies including PostgreSQL, MongoDB, and SQL Server",
   "Implemented comprehensive server deployment and configuration strategies, ensuring optimal performance and reliability of production environments",
   "Orchestrated enterprise collaboration tools ecosystem by setting up and maintaining local instances of Confluence, Jira, and secure VPN services",
   "Executed robust backup and disaster recovery solutions using Veeam, ensuring data integrity and business continuity",
   "Conducted comprehensive research on Hyperledger technologies, identifying and recommending optimal blockchain frameworks for diverse organizational needs",
   "Developed specialized blockchain services, including implementations of decentralized exchange (DEX) platforms, Wallet as a Service (WaaS), and blockchain-based voting systems",
   "Served as a key knowledge transfer resource, conducting technical training and knowledge sharing sessions on Hyperledger technologies for cross-functional teams",
   "Successfully implemented and operationalized a Hyperledger Fabric blockchain solution, demonstrating end-to-end expertise from research to production deployment"
]

############## Freelance config ################
#################################################
[[freelance]]
title = "Detecting Parasites in Pets Microscopic Images"
timeline = "Sep 2022 - April 2023"
city = "Berlin"
country = "Germany (Remote)"
description = "An <b>object detection system</b> to detect and locate pets parasites in microscopic images"
bullets = [
    "Utilized object detection models (YOLO, Faster RCNN, RetinaNet) to detect pets parasites.",
    "Designed a Flask web server to upload the samples and recieve the results.",
    "Deployed the project on an Amazon EC2 instance. (Delievered to a real laboratory)"
]

[[freelance]]
title = "Perfume Recommendation System"
timeline = "May 2024 — Oct 2024"
city = "Tehran"
country = "Iran"
description = "A system for <b>recommending perfumes</b> to customers in perfume shops"
bullets = [
    "Utilized clustering algorithms to cluster perfumes based on their accords and notes.",
    "Implemented a recommendation system based on users preference."
]

############## Teaching config ####################
#################################################

[[teaching]]
title = "Fundamentals of Programming"
timeline = "Fall 2020"
supervisor = "Dr. Hossein Zainali"

[[teaching]]
title = "Advanced Programming"
timeline = "Spring 2021"
supervisor = "Dr. Hossein Zeinali"


############## Certificates config ####################
#################################################
[[certificate]]
title = "Certificate of 2nd place - Tech Olympics 2024: Data Processing"
image = "./config/assets/certificates/dataProcessing_TechOlympics.png"
url = "https://quera.org/media/public/quera_certificate/b8fae211a6e54343994d1e4fc5f939b4.jpg"

[[certificate]]
title = "Certificate of 2nd place - Robocup IRAN OPEN 2018 (Echoic Team - Rescue Virtual Robot)"
image = "./config/assets/certificates/Echoic2.png"
url = "https://github.com/neginkheirmand/neginkheirmand.github.io/blob/master/config/assets/certificates/Echoic2.jpg?raw=true"

[[certificate]]
title = "Certificate of Participation - Robocup IRAN OPEN 2018 (Echoic Team - Rescue Virtual Robot)"
image = "./config/assets/certificates/Echoic1.png"
url = "https://github.com/neginkheirmand/neginkheirmand.github.io/blob/master/config/assets/certificates/Echoic1.jpg?raw=true"

[[certificate]]
title = "Structuring Machine Learning Projects"
image = "./config/assets/certificates/SMLP.png"

[[certificate]]
title = "Improving Deep Neural Networks"
image = "./config/assets/certificates/IDNN.png"

[[certificate]]
title = "NLP with Classification and Vector Spaces"
image = "./config/assets/certificates/NLPCV.png"

[[certificate]]
title = "NLP with Probabilistic Models"
image = "./config/assets/certificates/NLPPM.png"


############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "Web design"
value = "80%"

[[skill]]
title = "Graphic design"
value = "70%"

[[skill]]
title = "Branding"
value = "90%"

[[skill]]
title = "WordPress"
value = "50%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Ingles"
value = "60%"

[[language]]
title = "French"
value = "50%"