# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

# logo-facebook = "https://facebook.com/"
# logo-twitter = "https://twitter.com/"
logo-github = "https://github.com/neginkheirmand/"
chatbox-outline = "https://t.me/neginkheirmand"
# logo-linkedin = "https://www.linkedin.com/in/amirparsa-salmankhah-6b3681191/"
logo-instagram = "https://instagram.com/negin_kheirmand"
# logo-figma = "figma.com/"
# logo-youtube = "https://youtube.com/"
# logo-reddit = "https://www.reddit.com/"
logo-discord = "http://discordapp.com/users/741674999240458330"
# logo-pinterest = "https://www.pinterest.com/"